Repository usnistgov/pfhub, pull requests merged in 2018-10, with the labels that each got.

#901 PFHub Upload: Finite_Diff_B
  _data/charts/3a1_free_energy.json
  _data/charts/3a1_memory.json
  _data/charts/benchmark_upload.json
  _data/charts/code_upload.json
  _data/data_table.yaml
  _data/simulations/Finite_Diff_B/meta.yaml
Labels: upload

#902 PFHub Upload: Finite_Diff_C
  _data/charts/3a1_free_energy.json
  _data/charts/3a1_memory.json
  _data/charts/benchmark_upload.json
  _data/charts/code_upload.json
  _data/data_table.yaml
  _data/simulations/Finite_Diff_C/meta.yaml
Labels: upload

#904 PFHub Upload: Finite_Diff_A_update
  _data/simulations/Finite_Diff_A_update/meta.yaml
Labels: upload

#911 Switch prose.io edit links to use usnistgov
  _config.yml
Labels: bug

#906 Remove manual creation of efficiency data
  _data/benchmarks.yaml
  _includes/coffee/result_comparison.coffee
Labels: enhancement

#905 PFHub Upload: PRISMS_PF_3a_faster
  _data/simulations/PRISMS_PF_3a_faster/meta.yaml
Labels: upload

#907 Add link to the upload's pull-request
  _includes/coffee/simulation.coffee
  _includes/simulation.html
  js/simulation.coffee
Labels: enhancement

#916 Fix bug in efficiency plot
  _data/benchmarks.yaml
  _includes/coffee/result_comparison.coffee
Labels: bug

#917 Issue880 better repo link
  _includes/coffee/simulation.coffee
  _includes/coffee/test.coffee
  _includes/simulation.html
  css/chimad.css
Labels: bug
